version: "3.8"
services:
  app:
    build:
      context: ./
    networks:
    - gqlgen-gorm-example
    ports:
    - 8080:8080
    depends_on:
    - redis
    - mysql
    container_name: app
  redis:
    image: redis:6-alpine
    ports:
    - 6379:6379
    networks:
    - gqlgen-gorm-example
    container_name: redis
  mysql:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=root
    volumes:
    - ./sample.sql:/docker-entrypoint-initdb.d/sample.sql
    ports:
    - 3306:3306
    networks:
    - gqlgen-gorm-example
    container_name: mysql
networks:
  gqlgen-gorm-example:
    name: gqlgen-gorm-example